version: '3.8'

networks:
  red_proxy:
    ipam:
      config:
        - subnet: 172.20.0.0/24

  red_wordpress:
    internal: true
    ipam:
      config:
        - subnet: 172.20.1.0/24

  red_moodle:
    internal: true
    ipam:
      config:
        - subnet: 172.20.2.0/24

  red_inventario:
    internal: true
    ipam:
      config:
        - subnet: 172.20.3.0/24

services:

  # *** NGINX PROXY ***
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    hostname: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      red_proxy:
        ipv4_address: 172.20.0.10

 # *** DEFAULT ***
  default-front:
    build: ./images/default
    container_name: default-front
    environment:
      - IS_PROXY_HTTPS=on
    volumes:
      - ./images/default/html:/var/www/html
    ports:
      - "2021:21"
    networks:
      red_proxy:
        ipv4_address: 172.20.0.11

  # *** WORDPRESS ***
  wordpress-front:
    build: ./images/wordpress
    container_name: wordpress-front
    environment:
      - IS_PROXY_HTTPS=on
    hostname: wordpress-f.232v
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./images/wordpress/html:/var/www/html
    networks:
      red_proxy:
        ipv4_address: 172.20.0.21
      red_wordpress:
        ipv4_address: 172.20.1.21

  wordpress-back:
    image: mysql:8.0
    container_name: wordpress-back
    hostname: wordpress-b.232v
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASS}
    volumes:
      - ./mysql_data/wp:/var/lib/mysql
    networks:
      red_wordpress:
        ipv4_address: 172.20.1.20

  # *** MOODLE ***
  moodle-front:
    build: ./images/moodle
    container_name: moodle-front
    environment:
      - IS_PROXY_HTTPS=on
    hostname: moodle-f.232v
    ports:
      - "2221:21"
      - "22000-22010:22000-22010"
    volumes:
      - ./images/moodle/html:/var/www/html
      - ./moodledata:/var/www/moodledata
    networks:
      red_proxy:
        ipv4_address: 172.20.0.31
      red_moodle:
        ipv4_address: 172.20.2.31

  moodle-back:
    image: mysql:8.0
    container_name: moodle-back
    hostname: moodle-b.232v
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MOODLE_DB_NAME}
      MYSQL_USER: ${MOODLE_DB_USER}
      MYSQL_PASSWORD: ${MOODLE_DB_PASS}
    volumes:
      - ./mysql_data/moodle:/var/lib/mysql
    networks:
      red_moodle:
        ipv4_address: 172.20.2.20

  # *** INVENTARIO ***
  inventario-front:
    build: ./images/inventario
    container_name: inventario-front
    environment:
      - IS_PROXY_HTTPS=on
    hostname: inventario-f.232v
    ports:
      - "2321:21"
      - "23000-23010:23000-23010"
    volumes:
      - ./images/inventario/html:/var/www/html
    networks:
      red_proxy:
        ipv4_address: 172.20.0.41
      red_inventario:
        ipv4_address: 172.20.3.41

  inventario-back:
    image: mysql:8.0
    container_name: inventario-back
    hostname: inventario-b.232v
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${INV_DB_NAME}
      MYSQL_USER: ${INV_DB_USER}
      MYSQL_PASSWORD: ${INV_DB_PASS}
    volumes:
      - ./mysql_data/inventario:/var/lib/mysql
    networks:
      red_inventario:
        ipv4_address: 172.20.3.20
