listen=YES
listen_ipv6=NO

# Usuarios
anonymous_enable=NO
local_enable=YES
write_enable=YES

# Permisos
local_umask=022

# Chroot (encerrar usuario en su carpeta)
chroot_local_user=YES
allow_writeable_chroot=YES

# Directorio seguro
secure_chroot_dir=/var/run/vsftpd/empty

# Logs
xferlog_enable=YES

# Modo pasivo
pasv_enable=YES
pasv_min_port=22000
pasv_max_port=22010
pasv_address=172.16.23.90

# Opcional (mejora compatibilidad)
pasv_addr_resolve=NO
